### PR TITLE
Upgrade to Julia 1.7.

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by fredrikekre** [comment]
Segfault when precompiling in docker :|

**Comment by fredrikekre** [comment]
Guess it was just a fluke...

**Comment by fredrikekre** [comment]
Ok, Docker segfaults locally for me too. If I comment out this line: https://github.com/JuliaPackaging/PkgServer.jl/blob/06153726e4f756b800b9453df8a84bc4ccd6ca92/deps/precompile.jl#L4 it works though. It also works if I add `import Sockets` to that file. I wonder why that is required since there is already a `using Sockets` in PkgServer.jl...: https://github.com/JuliaPackaging/PkgServer.jl/blob/06153726e4f756b800b9453df8a84bc4ccd6ca92/src/PkgServer.jl#L12

**Comment by fredrikekre** [comment]
Managed to get an rr trace at least.

**Comment by vtjnash** [comment]
Traced this to https://github.com/staticfloat/FilesystemDatastructures.jl/issues/7 overwriting the type tags in memory, or random data on the stack, with zeros.

**Comment by fredrikekre** [comment]
Great thanks.

**Pull request merged**
