### PR TITLE
Add workflow for automatically updating the Manifest.toml

### PR DESCRIPTION
**Pull request by fredrikekre**
Add workflow for automatically updating the Manifest.toml, and hence the docker image.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Example PR here: https://github.com/fredrikekre/PkgServer.jl/pull/3

**Comment by fredrikekre** [comment]
Looks like the server  doesn't work in the docker image on Julia 1.5:
```
pkgserver_1   | ERROR: LoadError: Failed to precompile PkgServer [eac38ba3-4627-46d4-b1a1-bcb86ba22f8b] to /depot/compiled/v1.5/PkgServer/6eohG_jUZaQ.ji.
pkgserver_1   | Stacktrace:
pkgserver_1   |  [1] error(::String) at ./error.jl:33
pkgserver_1   |  [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1290
pkgserver_1   |  [3] _require(::Base.PkgId) at ./loading.jl:1030
pkgserver_1   |  [4] require(::Base.PkgId) at ./loading.jl:928
pkgserver_1   |  [5] require(::Module, ::Symbol) at ./loading.jl:923
pkgserver_1   |  [6] include(::Function, ::Module, ::String) at ./Base.jl:380
pkgserver_1   |  [7] include(::Module, ::String) at ./Base.jl:368
pkgserver_1   |  [8] exec_options(::Base.JLOptions) at ./client.jl:296
pkgserver_1   |  [9] _start() at ./client.jl:506
pkgserver_1   | in expression starting at /app/bin/run_server.jl:2
pkgserver_1   | ERROR: LoadError: InitError: could not load library "/depot/artifacts/519367e9365948074c1fcc9f4365597f147a5ab7/lib/libmbedcrypto.so"
pkgserver_1   | /depot/artifacts/519367e9365948074c1fcc9f4365597f147a5ab7/lib/libmbedcrypto.so: cannot open shared object file: Permission denied
pkgserver_1   | Stacktrace:
pkgserver_1   |  [1] dlopen(::String, ::UInt32; throw_error::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
pkgserver_1   |  [2] dlopen(::String, ::UInt32) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
pkgserver_1   |  [3] __init__() at /depot/packages/MbedTLS_jll/qGMUr/src/wrappers/x86_64-linux-gnu.jl:67
pkgserver_1   |  [4] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:697
pkgserver_1   |  [5] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:782
pkgserver_1   |  [6] _tryrequire_from_serialized(::Base.PkgId, ::UInt64, ::String) at ./loading.jl:712
pkgserver_1   |  [7] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:771
pkgserver_1   |  [8] _tryrequire_from_serialized(::Base.PkgId, ::UInt64, ::String) at ./loading.jl:712
pkgserver_1   |  [9] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:771
pkgserver_1   |  [10] _require(::Base.PkgId) at ./loading.jl:1007
pkgserver_1   |  [11] require(::Base.PkgId) at ./loading.jl:928
pkgserver_1   |  [12] require(::Module, ::Symbol) at ./loading.jl:923
pkgserver_1   |  [13] include(::Function, ::Module, ::String) at ./Base.jl:380
pkgserver_1   |  [14] include(::Module, ::String) at ./Base.jl:368
pkgserver_1   |  [15] top-level scope at none:2
pkgserver_1   |  [16] eval at ./boot.jl:331 [inlined]
pkgserver_1   |  [17] eval(::Expr) at ./client.jl:467
pkgserver_1   |  [18] top-level scope at ./none:3
pkgserver_1   | during initialization of module MbedTLS_jll
pkgserver_1   | in expression starting at /app/src/PkgServer.jl:4
```

**Comment by fredrikekre** [comment]
Skipped the update to Julia 1.5 for now.

**Comment by staticfloat** [comment]
Looks good to me!

**Pull request merged**
