### PR TITLE
Small fixes to get `gen_static.jl` working

### PR DESCRIPTION
**Pull request by staticfloat**
* We need `Dates` for things like `now()` and `DateTime`

* On Linux (e.g. non-BSD's), we use the names `zcat` and `tar` instead of `gzcat` and `gtar`.

It saddens me that my first instinct is to jump back into `PlatformEngines`-style nonsense.  Let's switch this over to `CodecZlib` and fully `Tar.jl` in the near future. :)

### CODE REVIEW

**Comment by johnnychen94** [comment]
Curious to ask, is it possible to get rid of `tar` and `gzip` with the existing feature of `CodecZlib` and `Tar`?

FYI, I'm [refactoring `gen_static.jl`](https://github.com/johnnychen94/StorageServer.jl/pull/1) with covering #5 in mind

**Comment by StefanKarpinski** [comment]
I can easily change this to use CodecZlib, so I'll just make a PR to do that.

**Comment by staticfloat** [comment]
Great; and then the last usage of `tar` is to list files; is `Tar.jl` capable of that?

**Comment by StefanKarpinski** [comment]
It is—that was just an oversight.

**Pull request closed without merging**
