### PR TITLE
Upgrade to Julia 1.6.

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by fredrikekre** [comment]
docker tests keep failing. curl can find the server but not HTTP.jl...

**Comment by fredrikekre** [comment]
I ssh'd to the worker and from a Julia REPL it works
```
julia> HTTP.get("http://localhost:8000/registries")
HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
```
but from running the tests it does not, https://github.com/JuliaPackaging/PkgServer.jl/blob/c057166756f1108b57fbfb1dbb0de4487b9e19c2/test/tests.jl#L31 keeps failing with `ECONNREFUSED`...

**Comment by fredrikekre** [comment]
Okay this is very strange, from a fresh Julia session:
```julia
julia> url = "http://localhost:8000/registries";

julia> run(`curl -I $url`)
HTTP/1.1 200 OK
Process(`curl -I http://localhost:8000/registries`, ProcessExited(0))

julia> HTTP.get(url; retry=false, readtimeout=1)
ERROR: IOError(Base.IOError("connect: connection refused (ECONNREFUSED)", -111) during request(http://localhost:8000/registries))

julia> HTTP.get(url)
HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
[...]
"""

julia> HTTP.get(url; retry=false, readtimeout=1)
HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
[...]
"""
```

**Comment by fredrikekre** [comment]
@staticfloat @quinnj any ideas? This does not seem to happen on Julia 1.5, and it only happens if the PkgServer is running in docker...

**Comment by fredrikekre** [comment]
Full stacktrace:
```
julia> HTTP.get(url; retry=false, readtimeout=1)
ERROR: IOError(Base.IOError("connect: connection refused (ECONNREFUSED)", -111) during request(http://localhost:8000/registries))

Stacktrace:
  [1] wait_connected(x::Sockets.TCPSocket)
    @ Sockets /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Sockets/src/Sockets.jl:532
  [2] getconnection(::Type{Sockets.TCPSocket}, host::SubString{String}, port::SubString{String}; keepalive::Bool, connect_timeout::Int64, readtimeout::Int64, kw::Base.Iterators.Pairs{Symbol, 
Union{Nothing, Bool}, NTuple{4, Symbol}, NamedTuple{(:require_ssl_verification, :iofunction, :reached_redirect_limit, :retry), Tuple{Bool, Nothing, Bool, Bool}}})
    @ HTTP.ConnectionPool ~/.julia/packages/HTTP/TVRTz/src/ConnectionPool.jl:672
  [3] newconnection(pod::HTTP.ConnectionPool.Pod, T::Type, host::SubString{String}, port::SubString{String}, pipeline_limit::Int64, require_ssl_verification::Bool, idle_timeout::Int64; kw::Ba
se.Iterators.Pairs{Symbol, Union{Nothing, Integer}, NTuple{4, Symbol}, NamedTuple{(:iofunction, :reached_redirect_limit, :retry, :readtimeout), Tuple{Nothing, Bool, Bool, Int64}}})
    @ HTTP.ConnectionPool ~/.julia/packages/HTTP/TVRTz/src/ConnectionPool.jl:618
  [4] getconnection(::Type{HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}, host::SubString{String}, port::SubString{String}; connection_limit::Int64, pipeline_limit::Int64, idle_timeout:
:Int64, reuse_limit::Int64, require_ssl_verification::Bool, kw::Base.Iterators.Pairs{Symbol, Union{Nothing, Integer}, NTuple{4, Symbol}, NamedTuple{(:iofunction, :reached_redirect_limit, :ret
ry, :readtimeout), Tuple{Nothing, Bool, Bool, Int64}}})
    @ HTTP.ConnectionPool ~/.julia/packages/HTTP/TVRTz/src/ConnectionPool.jl:562
  [5] request(::Type{ConnectionPoolLayer{DebugLayer{TimeoutLayer{StreamLayer{Union{}}}}}}, url::URIs.URI, req::HTTP.Messages.Request, body::Vector{UInt8}; proxy::Nothing, socket_type::Type, r
euse_limit::Int64, kw::Base.Iterators.Pairs{Symbol, Union{Nothing, Integer}, NTuple{4, Symbol}, NamedTuple{(:iofunction, :reached_redirect_limit, :retry, :readtimeout), Tuple{Nothing, Bool, B
ool, Int64}}})
    @ HTTP.ConnectionRequest ~/.julia/packages/HTTP/TVRTz/src/ConnectionRequest.jl:85
  [6] request(::Type{ExceptionLayer{ConnectionPoolLayer{DebugLayer{TimeoutLayer{StreamLayer{Union{}}}}}}}, ::URIs.URI, ::Vararg{Any, N} where N; kw::Base.Iterators.Pairs{Symbol, Union{Nothing
, Integer}, NTuple{4, Symbol}, NamedTuple{(:iofunction, :reached_redirect_limit, :retry, :readtimeout), Tuple{Nothing, Bool, Bool, Int64}}})
    @ HTTP.ExceptionRequest ~/.julia/packages/HTTP/TVRTz/src/ExceptionRequest.jl:19
  [7] request(::Type{MessageLayer{ExceptionLayer{ConnectionPoolLayer{DebugLayer{TimeoutLayer{StreamLayer{Union{}}}}}}}}, method::String, url::URIs.URI, headers::Vector{Pair{SubString{String},
 SubString{String}}}, body::Vector{UInt8}; http_version::VersionNumber, target::String, parent::Nothing, iofunction::Nothing, kw::Base.Iterators.Pairs{Symbol, Integer, Tuple{Symbol, Symbol, S
ymbol}, NamedTuple{(:reached_redirect_limit, :retry, :readtimeout), Tuple{Bool, Bool, Int64}}})
    @ HTTP.MessageRequest ~/.julia/packages/HTTP/TVRTz/src/MessageRequest.jl:59
  [8] request(::Type{BasicAuthLayer{MessageLayer{ExceptionLayer{ConnectionPoolLayer{DebugLayer{TimeoutLayer{StreamLayer{Union{}}}}}}}}}, method::String, url::URIs.URI, headers::Vector{Pair{Su
bString{String}, SubString{String}}}, body::Vector{UInt8}; kw::Base.Iterators.Pairs{Symbol, Integer, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:reached_redirect_limit, :retry, :readtimeout),
 Tuple{Bool, Bool, Int64}}})
    @ HTTP.BasicAuthRequest ~/.julia/packages/HTTP/TVRTz/src/BasicAuthRequest.jl:28
  [9] request(::Type{RedirectLayer{BasicAuthLayer{MessageLayer{ExceptionLayer{ConnectionPoolLayer{DebugLayer{TimeoutLayer{StreamLayer{Union{}}}}}}}}}}, method::String, url::URIs.URI, headers:
:Vector{Pair{SubString{String}, SubString{String}}}, body::Vector{UInt8}; redirect_limit::Int64, forwardheaders::Bool, kw::Base.Iterators.Pairs{Symbol, Integer, Tuple{Symbol, Symbol}, NamedTu
ple{(:retry, :readtimeout), Tuple{Bool, Int64}}})
    @ HTTP.RedirectRequest ~/.julia/packages/HTTP/TVRTz/src/RedirectRequest.jl:24
 [10] request(method::String, url::String, h::Vector{Pair{SubString{String}, SubString{String}}}, b::Vector{UInt8}; headers::Vector{Pair{SubString{String}, SubString{String}}}, body::Vector{U
Int8}, query::Nothing, kw::Base.Iterators.Pairs{Symbol, Integer, Tuple{Symbol, Symbol}, NamedTuple{(:retry, :readtimeout), Tuple{Bool, Int64}}})
    @ HTTP ~/.julia/packages/HTTP/TVRTz/src/HTTP.jl:315
 [11] #get#13
    @ ~/.julia/packages/HTTP/TVRTz/src/HTTP.jl:392 [inlined]
 [12] top-level scope
    @ REPL[10]:1
```

**Comment by staticfloat** [comment]
What addresses is the HTTP server listening on?  Use `netstat` to find out.  Is it listening on both IPv6 and IPv4?

**Comment by fredrikekre** [comment]
```
$ netstat -l --tcp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:http            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8084            0.0.0.0:*               LISTEN     
tcp        0      0 localhost:domain        0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN     
tcp        0      0 localhost:39289         0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:https           0.0.0.0:*               LISTEN     
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN
```

**Comment by staticfloat** [comment]
Okay so perhaps “localhost” resolves to the ipv6 address first, and when that fails it falls back to ipv4 but only if retry is set to true?

**Comment by fredrikekre** [comment]
Maybe, and that is cached for the second succesful connection then?

Could that explain why it works without Docker where the Julia process explicitly listens on `0.0.0.0` but with Docker the Docker daemon might listen on both ipv4 and ipv6 and forward both to the container?

**Comment by fredrikekre** [comment]
You are probably right btw, here is the curl output
```
* connect to ::1 port 8000 failed: Connection refused
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000 (#0)
```

**Comment by fredrikekre** [comment]
All green! But might be nice to hold off until 1.6 final (at least to a version that includes the Downloads.jl fixes etc).

**Comment by fredrikekre** [comment]
Updated. Might wanna hold off for a day until Julia 1.6 final is available on Docker hub.

**Comment by fredrikekre** [comment]
Ok, should be good to go now.

**Comment by staticfloat** [comment]
Looks good to me!  Thanks Fredrik!

**Pull request merged**
