### PR TITLE
Add `kr.storage.julialang.org` as a default upstream storage server

### PR DESCRIPTION
**Pull request by staticfloat**
This will cause our pkg servers in China, Korea, Singapore, etc... to generally pull from the KR server rather than the US server.

### CODE REVIEW

**Comment by johnnychen94** [comment]
:tada: Is the kr server fully functioning now? If so I could set the upstream of BFSU mirror to this.

Edit: Hmmm, looks like it's just a simple proxy to the US server?

**Comment by staticfloat** [comment]
The KR server is indeed fully functional, but no, it's not a simple proxy.  It stores things to S3 in a bucket in the `ap-northeast-2` S3 zone and redirects users to that bucket, when possible.

**Comment by StefanKarpinski** [comment]
> Edit: Hmmm, looks like it's just a simple proxy to the US server?

I'm curious how you'd know if it was a proxy or not?

**Comment by johnnychen94** [comment]
> I'm curious how you'd know if it was a proxy or not?

Ha! This should just be my misunderstanding; I tried to download the same content from both `us-east.storage` and `kr.storage` in Shanghai and it turns out that `us-east.storage` gives a 5Mb/s while `kr.storage` gives a 50Kb/s.

Thanks for the explanation.

**Comment by StefanKarpinski** [comment]
Huh, that’s really unfortunate. If the bandwidth from the kr.storage instance is that bad from everywhere then maybe we shouldn’t bother with it at all. @staticfloat, do you think we should try pulling from a few different places and see if the bandwidth is this bad from everywhere or if it’s the great firewall? It’s possible it treats US and Korean traffic differently and it’s actually better to go all the way to the US for this. Of course the package server uses the storage server that replies first so if the US server is faster then it may be picking it anyway.

**Comment by johnnychen94** [comment]
I bet it's due to the Great Firewall. My personal experience is that network connection from mainland China to AWS never gets a not bad.

**Comment by StefanKarpinski** [comment]
I'm not sure there's much to do here then. There are pkg servers inside of China now and they're backed by all of the storage servers and will use whichever one has the lowest latency to fetch cache misses from. The storage server in Korea is still useful outside of China (say in Korea or Japan), even if it's unhelpful for serving to China.

**Comment by staticfloat** [comment]
In my experience, this really depends on the time of day and where in China you're pulling from.  The Pkg servers themselves in the Huawei cloud datacenters right now are having a hard time pulling from either of the storage servers.  I think it's best to keep both storage servers up, (especially for other pkg servers outside of China) but make use of the BFSU storage server upstream as much as possible.

**Comment by StefanKarpinski** [comment]
We should definitely add BSFU as a storage server for the China pkg servers. It doesn’t need to be on the list for any other pkg servers since it’s static and won’t do anything with requests for resources that aren’t reachable from the registry.

**Comment by johnnychen94** [comment]
Here's some information about the BFSU server that may help:

Currently, incremental fetching in the BFSU server hangs for unidentified reasons so I added a timeout option there to make sure it gets skipped when it hangs. For this reason, BFSU should not be considered as complete as other storage servers.

Also, the cron job in the BFSU server starts per hour. Thus it is less likely be the server with the latest registries.

It seems that we need to add a sorting strategy to prioritize the BFSU server when fetching resources. I can try this out if you don't have plans on this. The way I have in mind is to regularly download one available registry from all upstream and time it, which I think is more reliable than checking the ping time.

**Comment by staticfloat** [comment]
> It seems that we need to add a sorting strategy to prioritize the BFSU server when fetching resources.

The Pkg server already does this; when it makes a request for a resource it doesn't have, it sends simultaneous HEAD requests to each storage server it is connected to, then it downloads from whichever responds the fastest.

> For this reason, BFSU should not be considered as complete as other storage servers.

Luckily, that's not a problem!  The Pkg server will ask it for resources, but because it returns a 404, it won't try to download from there.

**Pull request merged**
