### PR TITLE
Better nginx logging

### PR DESCRIPTION
**Pull request by staticfloat**
This showcases how to log important information like response time, bytes transmitted, etc... for each request made to the PkgServer.  We can analyze the logs after the fact in order to extract information such as the "long tail" of package requests, which IPs are costing us the most bandwidth (in order to determine whether we need to add edge caches) etc...

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
We'll also want to log all the telemetry info sent in headers by the clients. That should all be aggregated and published somehow, but that's a whole other process.

**Comment by StefanKarpinski** [comment]
Oh, also, I guess that's a totally separate logging layer from this anyway, although we could potentially log it here, but we could also log it from the Julia backend.

**Comment by staticfloat** [comment]
We can add telemetry headers by adding things like `$http_Julia-Version` and `$http_Julia-Salt-Hash` to the common log format.  I think since we're already logging stuff here, might as well.  I'll add it in and we can see if it works.

**Comment by StefanKarpinski** [comment]
Can confirm that works. The page I tried before is no doubt cached somewhere.

**Comment by StefanKarpinski** [comment]
It should probably record any header that starts with `Julia-`.

**Comment by staticfloat** [comment]
I don't think nginx can do that, unfortunately.

**Comment by staticfloat** [comment]
Alright, I had to munge the header names a bit, but it seems to be working now.  This probably isn't the only way we want to do this; there may be situations where we don't want to use `nginx` on the front, or getting those logs is inconvenient, etc.... but as an example of how to do it, (And as a convenient place where we have a lot of interesting log data in one convenient, easy-to-parse format) it's useful.

**Pull request merged**
