### PR TITLE
Fix signature of `ccall`

### LINKED ISSUE #154: Issue running server: LoadError: ccall method definition: return type doesn't correspond to a C type
```julia
❯ julia --project bin/run_server.jl
ERROR: LoadError: ccall method definition: return type doesn't correspond to a C type
Stacktrace:
 [1] top-level scope
   @ ~/PkgServer.jl/src/meta.jl:165
 [2] include(mod::Module, _path::String)
   @ Base ./Base.jl:422
 [3] include(x::String)
   @ PkgServer ~/PkgServer.jl/src/PkgServer.jl:1
 [4] top-level scope
   @ ~/PkgServer.jl/src/PkgServer.jl:20
 [5] include
   @ ./Base.jl:422 [inlined]
 [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base ./loading.jl:1400
 [7] top-level scope
   @ stdin:1
in expression starting at /home/mus/PkgServer.jl/src/meta.jl:165
in expression starting at /home/mus/PkgServer.jl/src/PkgServer.jl:1
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile PkgServer [eac38ba3-4627-46d4-b1a1-bcb86ba22f8b] to /home/mus/.julia/compiled/v1.8/PkgServer/jl_ynZB3D.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
   @ Base ./loading.jl:1551
 [3] compilecache
   @ ./loading.jl:1495 [inlined]
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1199
 [5] _require_prelocked(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1084
 [6] macro expansion
   @ ./loading.jl:1064 [inlined]
 [7] macro expansion
   @ ./lock.jl:223 [inlined]
 [8] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1028
in expression starting at /home/mus/PkgServer.jl/bin/run_server.jl:2

```

### PR DESCRIPTION
**Pull request by giordano**
Fix #154.  CC: @musm

### CODE REVIEW

**Comment by giordano** [comment]
~This works in Julia `master`, where I tried it, but not in v1.7.  Cool.~  Oh, no, the job just died by itself?

**Comment by DilumAluthge** [comment]
Presumably, one of the jobs needs a secret that's not available on fork jobs.

**Comment by giordano** [comment]
This might explain why I had to create the fork, I opened previous PRs from branches of this repo, which isn't what I usually do.  Sigh.

**Comment by DilumAluthge** [comment]
Since the no-secret job passed, it might be fine to just merge this (once approved) and then make sure that the CI job passes on master (and revert the PR job fails on master).

**Comment by DilumAluthge** [comment]
CI is all green on master.

**Pull request merged**
