### PR TITLE
CI: `docker build` on every PR; `docker push` iff running on a commit pushed to `master`

### LINKED ISSUE #135: perform docker build
Since Docker hub doesn't do automated builds for us anymore, let's do the build ourselves on CI.

@DilumAluthge can I enlist your help in setting up a job that does the following steps:

```
echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
docker build -t juliapackaging/pkgserver.jl .
```

On every PR, and then also does:
```
docker push juliapackaging/pkgserver.jl
```

If running on a commit that was merged to `master`?

### PR DESCRIPTION
**Pull request by DilumAluthge**
Fixes #135 

On every PR:
- `docker login`
- `docker build`

Only on commits pushed to `master`:
- `docker push`

Note: we don't do the Docker build if the test suite fails, with the rationale that we don't want to build and push a broken Docker image.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@staticfloat @giordano This is now ready to review.

The one tricky part, of course, is that we can't check that the `docker push` step works until we merge this into `master`.

So, our options for testing the `docker push` step are:
1. YOLO merge into `master` and see what happens
2. Temporarily edit the workflow file to perform the `docker push` step on pushes to the `dpa/build` branch. This will allow us to test that the `docker push` works correctly before we merge this PR. Of course, we have to remember to revert those changes before we merge the PR.

Let me know if you want to do option 2, and I'll push those changes.

**Review by staticfloat — APPROVED** [review]

**Comment by staticfloat** [comment]
Cowabunga it is

**Comment by DilumAluthge** [comment]
@staticfloat https://github.com/JuliaPackaging/PkgServer.jl/runs/3407521250

```

Run docker push juliapackaging/pkgserver.jl
  docker push juliapackaging/pkgserver.jl
  shell: /usr/bin/bash -e {0}
Using default tag: latest
The push refers to repository [docker.io/juliapackaging/pkgserver.jl]
62e7fc6eceec: Preparing
303483fcc272: Preparing
3a9796376282: Preparing
41228bb948d1: Preparing
e4dc8ac03c16: Preparing
fe5efa676339: Preparing
46adadf30176: Preparing
f149a5827519: Preparing
021c53668a03: Preparing
f68ef921efae: Preparing
fe5efa676339: Waiting
46adadf30176: Waiting
f149a5827519: Waiting
021c53668a03: Waiting
f68ef921efae: Waiting
denied: requested access to the resource is denied
Error: Process completed with exit code 1.
```

**Comment by DilumAluthge** [comment]
Can you double-check that the `DOCKER_USERNAME` user has write access to the Docker repo?

**Pull request merged**
